#DATABASE

MY_SQL_USERNAME: root
MY_SQL_PASSWORD: root
MY_SQL_HOST: 192.168.1.216
MY_SQL_PORT: 5432
MY_SQL_DB: spcloud

#SERVER

SERVER_PORT: 9090
ACTIVE_PROFILE: dev

#Email Config

EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 558
EMAIL_ID: <YOUR EMAIL ID>
EMAIL_PASSWORD: <YOUR APP PASSWORD>
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
